/* Vocab 400 CET-4 words, Day 1-10 x 40 words */
/* Source: docs/vocab-400.md */

export interface VocabWord {
  w: string;  /* word */
  p: string;  /* phonetic */
  d: string;  /* meaning */
  e: string;  /* example */
}

export interface VocabDay {
  day: number;
  words: VocabWord[];
}

export const VOCAB_DAYS: VocabDay[] = [
  {
    day: 1,
    words: [
      { w: "abandon", p: "/əˈbændən/", d: "v. 抛弃；放弃", e: "He abandoned his car in the snow." },
      { w: "ability", p: "/əˈbɪləti/", d: "n. 能力；才能", e: "She has the ability to learn fast." },
      { w: "absence", p: "/ˈæbsəns/", d: "n. 缺席；缺乏", e: "His absence was noticed." },
      { w: "absent", p: "/ˈæbsənt/", d: "adj. 缺席的；心不在焉的", e: "He was absent from class." },
      { w: "absolute", p: "/ˈæbsəluːt/", d: "adj. 绝对的；完全的", e: "absolute power" },
      { w: "absorb", p: "/əbˈzɔːb/", d: "v. 吸收；使专注", e: "The sponge absorbs water." },
      { w: "abstract", p: "/ˈæbstrækt/", d: "adj. 抽象的 n. 摘要", e: "an abstract concept" },
      { w: "abundant", p: "/əˈbʌndənt/", d: "adj. 丰富的；充裕的", e: "abundant resources" },
      { w: "academic", p: "/ˌækəˈdemɪk/", d: "adj. 学术的；学院的", e: "academic research" },
      { w: "accelerate", p: "/əkˈseləreɪt/", d: "v. 加速；促进", e: "The car accelerated." },
      { w: "accept", p: "/əkˈsept/", d: "v. 接受；同意", e: "accept an offer" },
      { w: "access", p: "/ˈækses/", d: "n. 通道；使用权 v. 访问", e: "have access to the Internet" },
      { w: "accident", p: "/ˈæksɪdənt/", d: "n. 意外；事故", e: "a car accident" },
      { w: "accompany", p: "/əˈkʌmpəni/", d: "v. 陪伴；伴随", e: "She accompanied me home." },
      { w: "accomplish", p: "/əˈkʌmplɪʃ/", d: "v. 完成；实现", e: "accomplish a goal" },
      { w: "according", p: "/əˈkɔːdɪŋ/", d: "adv. 依照", e: "according to the report" },
      { w: "account", p: "/əˈkaʊnt/", d: "n. 账户；描述 v. 解释", e: "a bank account" },
      { w: "accurate", p: "/ˈækjərət/", d: "adj. 准确的；精确的", e: "an accurate answer" },
      { w: "accuse", p: "/əˈkjuːz/", d: "v. 指责；控告", e: "accuse him of lying" },
      { w: "achieve", p: "/əˈtʃiːv/", d: "v. 达到；实现", e: "achieve success" },
      { w: "acquire", p: "/əˈkwaɪə/", d: "v. 获得；习得", e: "acquire knowledge" },
      { w: "active", p: "/ˈæktɪv/", d: "adj. 积极的；活跃的", e: "an active lifestyle" },
      { w: "actual", p: "/ˈæktʃuəl/", d: "adj. 实际的；真实的", e: "the actual cost" },
      { w: "adapt", p: "/əˈdæpt/", d: "v. 适应；改编", e: "adapt to a new environment" },
      { w: "adequate", p: "/ˈædɪkwət/", d: "adj. 足够的；适当的", e: "adequate preparation" },
      { w: "adjust", p: "/əˈdʒʌst/", d: "v. 调整；适应", e: "adjust the seat" },
      { w: "admire", p: "/ədˈmaɪə/", d: "v. 钦佩；欣赏", e: "I admire your courage." },
      { w: "admission", p: "/ədˈmɪʃn/", d: "n. 承认；入场费；录取", e: "admission to college" },
      { w: "adopt", p: "/əˈdɒpt/", d: "v. 采用；收养", e: "adopt a child" },
      { w: "advance", p: "/ədˈvɑːns/", d: "v. 推进；前进 n. 进步", e: "in advance" },
      { w: "advantage", p: "/ədˈvɑːntɪdʒ/", d: "n. 优势；好处", e: "take advantage of" },
      { w: "adventure", p: "/ədˈventʃə/", d: "n. 冒险；奇遇", e: "a great adventure" },
      { w: "advise", p: "/ədˈvaɪz/", d: "v. 建议；劝告", e: "advise him to leave" },
      { w: "affair", p: "/əˈfeə/", d: "n. 事务；事件", e: "foreign affairs" },
      { w: "affect", p: "/əˈfekt/", d: "v. 影响；感动", e: "The weather affects mood." },
      { w: "afford", p: "/əˈfɔːd/", d: "v. 负担得起", e: "can't afford a car" },
      { w: "afraid", p: "/əˈfreɪd/", d: "adj. 害怕的", e: "afraid of the dark" },
      { w: "agency", p: "/ˈeɪdʒənsi/", d: "n. 代理；机构", e: "a travel agency" },
      { w: "agenda", p: "/əˈdʒendə/", d: "n. 议程；日程", e: "the meeting agenda" },
      { w: "alarm", p: "/əˈlɑːm/", d: "n. 警报；惊恐 v. 使惊恐", e: "set the alarm" },
    ],
  },
  {
    day: 2,
    words: [
      { w: "alcohol", p: "/ˈælkəhɒl/", d: "n. 酒精；酒", e: "avoid alcohol" },
      { w: "alert", p: "/əˈlɜːt/", d: "adj. 警觉的 v. 警告", e: "stay alert" },
      { w: "alike", p: "/əˈlaɪk/", d: "adj. 相似的 adv. 同样地", e: "They look alike." },
      { w: "alive", p: "/əˈlaɪv/", d: "adj. 活着的；活跃的", e: "keep the dream alive" },
      { w: "allow", p: "/əˈlaʊ/", d: "v. 允许", e: "allow smoking" },
      { w: "alter", p: "/ˈɔːltə/", d: "v. 改变；修改", e: "alter the plan" },
      { w: "alternative", p: "/ɔːlˈtɜːnətɪv/", d: "n. 选择 adj. 可替代的", e: "an alternative plan" },
      { w: "amateur", p: "/ˈæmətə/", d: "adj. 业余的 n. 业余爱好者", e: "an amateur painter" },
      { w: "amazing", p: "/əˈmeɪzɪŋ/", d: "adj. 令人惊异的", e: "an amazing view" },
      { w: "ambition", p: "/æmˈbɪʃn/", d: "n. 雄心；抱负", e: "his political ambition" },
      { w: "analyze", p: "/ˈænəlaɪz/", d: "v. 分析", e: "analyze the data" },
      { w: "ancestor", p: "/ˈænsestə/", d: "n. 祖先；祖宗", e: "honor our ancestors" },
      { w: "ancient", p: "/ˈeɪnʃənt/", d: "adj. 古代的；古老的", e: "ancient history" },
      { w: "angle", p: "/ˈæŋɡl/", d: "n. 角度；观点", e: "from a different angle" },
      { w: "annoy", p: "/əˈnɔɪ/", d: "v. 使恼怒", e: "His noise annoyed me." },
      { w: "annual", p: "/ˈænjuəl/", d: "adj. 每年的 n. 年鉴", e: "annual report" },
      { w: "anticipate", p: "/ænˈtɪsɪpeɪt/", d: "v. 预期；预料", e: "anticipate problems" },
      { w: "anxiety", p: "/æŋˈzaɪəti/", d: "n. 焦虑；忧虑", e: "feel anxiety before exams" },
      { w: "apart", p: "/əˈpɑːt/", d: "adv. 分开；相隔", e: "take apart" },
      { w: "apparent", p: "/əˈpærənt/", d: "adj. 明显的；表面的", e: "for no apparent reason" },
      { w: "appeal", p: "/əˈpiːl/", d: "v. 呼吁；吸引 n. 吸引力", e: "appeal to young people" },
      { w: "appear", p: "/əˈpɪə/", d: "v. 出现；似乎", e: "He appeared calm." },
      { w: "appetite", p: "/ˈæpɪtaɪt/", d: "n. 胃口；欲望", e: "a good appetite" },
      { w: "applause", p: "/əˈplɔːz/", d: "n. 掌声", e: "receive applause" },
      { w: "apply", p: "/əˈplaɪ/", d: "v. 申请；应用", e: "apply for a job" },
      { w: "appoint", p: "/əˈpɔɪnt/", d: "v. 任命；约定", e: "appoint a manager" },
      { w: "appreciate", p: "/əˈpriːʃieɪt/", d: "v. 欣赏；感激", e: "I appreciate your help." },
      { w: "approach", p: "/əˈprəʊtʃ/", d: "v. 接近 n. 方法", e: "a new approach" },
      { w: "appropriate", p: "/əˈprəʊpriət/", d: "adj. 合适的", e: "appropriate behavior" },
      { w: "approve", p: "/əˈpruːv/", d: "v. 批准；赞成", e: "approve the plan" },
      { w: "approximate", p: "/əˈprɒksɪmət/", d: "adj. 近似的 v. 接近", e: "approximate cost" },
      { w: "arbitrary", p: "/ˈɑːbɪtrəri/", d: "adj. 任意的；武断的", e: "an arbitrary decision" },
      { w: "architect", p: "/ˈɑːkɪtekt/", d: "n. 建筑师；设计者", e: "a famous architect" },
      { w: "argue", p: "/ˈɑːɡjuː/", d: "v. 争论；主张", e: "argue for change" },
      { w: "arise", p: "/əˈraɪz/", d: "v. 出现；升起", e: "problems arise" },
      { w: "armed", p: "/ɑːmd/", d: "adj. 武装的", e: "armed forces" },
      { w: "arrange", p: "/əˈreɪndʒ/", d: "v. 安排；整理", e: "arrange a meeting" },
      { w: "arrest", p: "/əˈrest/", d: "v. 逮捕；拘留", e: "under arrest" },
      { w: "arrival", p: "/əˈraɪvl/", d: "n. 到达", e: "on arrival" },
      { w: "article", p: "/ˈɑːtɪkl/", d: "n. 文章；条款；物品", e: "a newspaper article" },
    ],
  },
  {
    day: 3,
    words: [
      { w: "artificial", p: "/ˌɑːtɪˈfɪʃl/", d: "adj. 人造的；虚假的", e: "artificial intelligence" },
      { w: "ashamed", p: "/əˈʃeɪmd/", d: "adj. 羞愧的", e: "ashamed of his mistake" },
      { w: "aspect", p: "/ˈæspekt/", d: "n. 方面；外观", e: "every aspect of life" },
      { w: "assess", p: "/əˈses/", d: "v. 评估；评定", e: "assess the risk" },
      { w: "assign", p: "/əˈsaɪn/", d: "v. 分配；指派", e: "assign homework" },
      { w: "assist", p: "/əˈsɪst/", d: "v. 帮助；协助", e: "assist the elderly" },
      { w: "associate", p: "/əˈsəʊʃieɪt/", d: "v. 联想；联系", e: "associate red with danger" },
      { w: "assume", p: "/əˈsjuːm/", d: "v. 假定；承担", e: "assume responsibility" },
      { w: "assure", p: "/əˈʃʊə/", d: "v. 保证；使确信", e: "I assure you it's safe." },
      { w: "astonish", p: "/əˈstɒnɪʃ/", d: "v. 使惊讶", e: "The news astonished us." },
      { w: "athlete", p: "/ˈæθliːt/", d: "n. 运动员", e: "a professional athlete" },
      { w: "atmosphere", p: "/ˈætməsfɪə/", d: "n. 大气；氛围", e: "a friendly atmosphere" },
      { w: "attach", p: "/əˈtætʃ/", d: "v. 附上；系", e: "attach a file" },
      { w: "attack", p: "/əˈtæk/", d: "v. 攻击；抨击 n. 袭击", e: "a heart attack" },
      { w: "attempt", p: "/əˈtempt/", d: "v. 试图 n. 尝试", e: "attempt to escape" },
      { w: "attract", p: "/əˈtrækt/", d: "v. 吸引", e: "attract attention" },
      { w: "audience", p: "/ˈɔːdiəns/", d: "n. 观众；听众", e: "a large audience" },
      { w: "authority", p: "/ɔːˈθɒrəti/", d: "n. 权威；当局", e: "the local authority" },
      { w: "automatic", p: "/ˌɔːtəˈmætɪk/", d: "adj. 自动的", e: "automatic doors" },
      { w: "available", p: "/əˈveɪləbl/", d: "adj. 可获得的；有空的", e: "tickets available" },
      { w: "average", p: "/ˈævərɪdʒ/", d: "adj. 平均的 n. 平均", e: "above average" },
      { w: "avoid", p: "/əˈvɔɪd/", d: "v. 避免", e: "avoid mistakes" },
      { w: "awake", p: "/əˈweɪk/", d: "adj. 醒着的 v. 唤醒", e: "stay awake" },
      { w: "award", p: "/əˈwɔːd/", d: "n. 奖 v. 授予", e: "win an award" },
      { w: "aware", p: "/əˈweə/", d: "adj. 意识到的", e: "aware of the danger" },
      { w: "awful", p: "/ˈɔːfl/", d: "adj. 糟糕的；可怕的", e: "awful weather" },
      { w: "bachelor", p: "/ˈbætʃələ/", d: "n. 学士；单身汉", e: "a bachelor's degree" },
      { w: "background", p: "/ˈbækɡraʊnd/", d: "n. 背景", e: "family background" },
      { w: "balance", p: "/ˈbæləns/", d: "n. 平衡；余额 v. 平衡", e: "keep balance" },
      { w: "ban", p: "/bæn/", d: "v. 禁止 n. 禁令", e: "ban smoking" },
      { w: "barrier", p: "/ˈbæriə/", d: "n. 障碍；屏障", e: "language barrier" },
      { w: "basis", p: "/ˈbeɪsɪs/", d: "n. 基础", e: "on a daily basis" },
      { w: "behalf", p: "/bɪˈhɑːf/", d: "n. 利益；代表", e: "on behalf of" },
      { w: "behave", p: "/bɪˈheɪv/", d: "v. 表现；举止", e: "behave well" },
      { w: "belief", p: "/bɪˈliːf/", d: "n. 信念；相信", e: "a strong belief" },
      { w: "belong", p: "/bɪˈlɒŋ/", d: "v. 属于", e: "belong to me" },
      { w: "beneficial", p: "/ˌbenɪˈfɪʃl/", d: "adj. 有益的", e: "beneficial to health" },
      { w: "betray", p: "/bɪˈtreɪ/", d: "v. 背叛；泄露", e: "betray a friend" },
      { w: "bias", p: "/ˈbaɪəs/", d: "n. 偏见 v. 使有偏见", e: "cultural bias" },
      { w: "bid", p: "/bɪd/", d: "v. 出价；投标 n. 努力", e: "bid for the contract" },
    ],
  },
  {
    day: 4,
    words: [
      { w: "blame", p: "/bleɪm/", d: "v. 责备 n. 责任", e: "blame him for the error" },
      { w: "blank", p: "/blæŋk/", d: "adj. 空白的 n. 空白", e: "a blank page" },
      { w: "blast", p: "/blɑːst/", d: "n. 爆炸；一阵 v. 炸", e: "a blast of wind" },
      { w: "blind", p: "/blaɪnd/", d: "adj. 盲的；盲目的", e: "blind faith" },
      { w: "block", p: "/blɒk/", d: "n. 块；街区 v. 阻挡", e: "a block of flats" },
      { w: "boast", p: "/bəʊst/", d: "v. 自夸", e: "boast about his wealth" },
      { w: "bold", p: "/bəʊld/", d: "adj. 大胆的；粗体的", e: "a bold plan" },
      { w: "bond", p: "/bɒnd/", d: "n. 纽带；债券 v. 结合", e: "a strong bond" },
      { w: "boost", p: "/buːst/", d: "v. 提升；促进 n. 推动", e: "boost confidence" },
      { w: "boundary", p: "/ˈbaʊndri/", d: "n. 边界；界限", e: "the boundary line" },
      { w: "brace", p: "/breɪs/", d: "v. 支撑；使做好准备", e: "brace for impact" },
      { w: "brain", p: "/breɪn/", d: "n. 大脑；智力", e: "use your brain" },
      { w: "branch", p: "/brɑːntʃ/", d: "n. 树枝；分支", e: "a bank branch" },
      { w: "brand", p: "/brænd/", d: "n. 品牌 v. 打烙印", e: "a famous brand" },
      { w: "breach", p: "/briːtʃ/", d: "n. 违背；缺口 v. 违反", e: "breach of contract" },
      { w: "brief", p: "/briːf/", d: "adj. 简短的 v. 简要介绍", e: "a brief meeting" },
      { w: "brilliant", p: "/ˈbrɪljənt/", d: "adj. 杰出的；明亮的", e: "a brilliant idea" },
      { w: "broaden", p: "/ˈbrɔːdn/", d: "v. 拓宽", e: "broaden one's horizons" },
      { w: "budget", p: "/ˈbʌdʒɪt/", d: "n. 预算 v. 编预算", e: "a tight budget" },
      { w: "burden", p: "/ˈbɜːdn/", d: "n. 负担 v. 使负重", e: "a heavy burden" },
      { w: "bureau", p: "/ˈbjʊərəʊ/", d: "n. 局；办事处", e: "a travel bureau" },
      { w: "burst", p: "/bɜːst/", d: "v. 爆发；破裂", e: "burst into tears" },
      { w: "calculate", p: "/ˈkælkjuleɪt/", d: "v. 计算；估计", e: "calculate the cost" },
      { w: "calm", p: "/kɑːm/", d: "adj. 平静的 v. 使平静", e: "keep calm" },
      { w: "campaign", p: "/kæmˈpeɪn/", d: "n. 运动；战役", e: "an ad campaign" },
      { w: "cancel", p: "/ˈkænsl/", d: "v. 取消", e: "cancel the order" },
      { w: "candidate", p: "/ˈkændɪdət/", d: "n. 候选人；应试者", e: "a presidential candidate" },
      { w: "capable", p: "/ˈkeɪpəbl/", d: "adj. 有能力的", e: "capable of winning" },
      { w: "capacity", p: "/kəˈpæsəti/", d: "n. 容量；能力", e: "a large capacity" },
      { w: "capture", p: "/ˈkæptʃə/", d: "v. 捕获；吸引", e: "capture the moment" },
      { w: "career", p: "/kəˈrɪə/", d: "n. 职业；生涯", e: "a successful career" },
      { w: "caution", p: "/ˈkɔːʃn/", d: "n. 谨慎；警告 v. 警告", e: "use caution" },
      { w: "cease", p: "/siːs/", d: "v. 停止", e: "cease fire" },
      { w: "celebrate", p: "/ˈselɪbreɪt/", d: "v. 庆祝", e: "celebrate a birthday" },
      { w: "challenge", p: "/ˈtʃælɪndʒ/", d: "n. 挑战 v. 质疑", e: "face a challenge" },
      { w: "chamber", p: "/ˈtʃeɪmbə/", d: "n. 房间；议院", e: "the chamber of commerce" },
      { w: "channel", p: "/ˈtʃænl/", d: "n. 频道；渠道 v. 引导", e: "a TV channel" },
      { w: "chaos", p: "/ˈkeɪɒs/", d: "n. 混乱", e: "in chaos" },
      { w: "charity", p: "/ˈtʃærəti/", d: "n. 慈善；施舍", e: "a charity event" },
      { w: "charm", p: "/tʃɑːm/", d: "n. 魅力 v. 吸引", e: "her natural charm" },
    ],
  },
  {
    day: 5,
    words: [
      { w: "chase", p: "/tʃeɪs/", d: "v. 追逐；追求", e: "chase a dream" },
      { w: "cheat", p: "/tʃiːt/", d: "v. 欺骗；作弊 n. 骗子", e: "cheat on a test" },
      { w: "cheerful", p: "/ˈtʃɪəfl/", d: "adj. 快乐的", e: "a cheerful smile" },
      { w: "cherish", p: "/ˈtʃerɪʃ/", d: "v. 珍爱；怀抱", e: "cherish the memory" },
      { w: "chief", p: "/tʃiːf/", d: "adj. 主要的 n. 首领", e: "the chief reason" },
      { w: "circumstance", p: "/ˈsɜːkəmstəns/", d: "n. 环境；情况", e: "under no circumstances" },
      { w: "cite", p: "/saɪt/", d: "v. 引用；传讯", e: "cite a source" },
      { w: "civil", p: "/ˈsɪvl/", d: "adj. 公民的；民用的", e: "civil rights" },
      { w: "claim", p: "/kleɪm/", d: "v. 声称；索赔 n. 主张", e: "claim damages" },
      { w: "clarify", p: "/ˈklærəfaɪ/", d: "v. 澄清；阐明", e: "clarify the point" },
      { w: "clash", p: "/klæʃ/", d: "v. 冲突；碰撞 n. 冲突", e: "a clash of opinions" },
      { w: "classic", p: "/ˈklæsɪk/", d: "adj. 经典的 n. 名著", e: "a classic novel" },
      { w: "clarity", p: "/ˈklærəti/", d: "n. 清晰", e: "with clarity" },
      { w: "clause", p: "/klɔːz/", d: "n. 条款；从句", e: "a contract clause" },
      { w: "clever", p: "/ˈklevə/", d: "adj. 聪明的", e: "a clever idea" },
      { w: "client", p: "/ˈklaɪənt/", d: "n. 客户；委托人", e: "a loyal client" },
      { w: "climate", p: "/ˈklaɪmət/", d: "n. 气候；风气", e: "a dry climate" },
      { w: "cling", p: "/klɪŋ/", d: "v. 坚持；附着", e: "cling to hope" },
      { w: "clue", p: "/kluː/", d: "n. 线索", e: "find a clue" },
      { w: "coach", p: "/kəʊtʃ/", d: "n. 教练；长途汽车 v. 指导", e: "a life coach" },
      { w: "coarse", p: "/kɔːs/", d: "adj. 粗糙的；粗俗的", e: "coarse cloth" },
      { w: "collapse", p: "/kəˈlæps/", d: "v. 倒塌；崩溃", e: "the bridge collapsed" },
      { w: "colleague", p: "/ˈkɒliːɡ/", d: "n. 同事", e: "a trusted colleague" },
      { w: "combat", p: "/ˈkɒmbæt/", d: "n. 战斗 v. 斗争", e: "combat pollution" },
      { w: "combine", p: "/kəmˈbaɪn/", d: "v. 结合", e: "combine work and study" },
      { w: "comfort", p: "/ˈkʌmfət/", d: "n. 舒适；安慰 v. 安慰", e: "a comfort zone" },
      { w: "command", p: "/kəˈmɑːnd/", d: "v. 命令；掌握 n. 指挥", e: "command respect" },
      { w: "comment", p: "/ˈkɒment/", d: "n. 评论 v. 评论", e: "no comment" },
      { w: "commit", p: "/kəˈmɪt/", d: "v. 犯(错)；承诺", e: "commit a crime" },
      { w: "community", p: "/kəˈmjuːnəti/", d: "n. 社区；团体", e: "the local community" },
      { w: "compact", p: "/ˈkɒmpækt/", d: "adj. 紧凑的；小巧的", e: "a compact car" },
      { w: "company", p: "/ˈkʌmpəni/", d: "n. 公司；陪伴", e: "keep someone company" },
      { w: "compare", p: "/kəmˈpeə/", d: "v. 比较", e: "compare A with B" },
      { w: "compensate", p: "/ˈkɒmpenseɪt/", d: "v. 补偿；赔偿", e: "compensate for the loss" },
      { w: "compete", p: "/kəmˈpiːt/", d: "v. 竞争", e: "compete for the prize" },
      { w: "compile", p: "/kəmˈpaɪl/", d: "v. 汇编；编辑", e: "compile a report" },
      { w: "complex", p: "/ˈkɒmpleks/", d: "adj. 复杂的 n. 综合体", e: "a complex problem" },
      { w: "component", p: "/kəmˈpəʊnənt/", d: "n. 成分；部件", e: "a key component" },
      { w: "compose", p: "/kəmˈpəʊz/", d: "v. 组成；创作", e: "compose a song" },
      { w: "comprehensive", p: "/ˌkɒmprɪˈhensɪv/", d: "adj. 综合的；全面的", e: "a comprehensive plan" },
    ],
  },
  {
    day: 6,
    words: [
      { w: "compromise", p: "/ˈkɒmprəmaɪz/", d: "n. 妥协 v. 妥协", e: "reach a compromise" },
      { w: "compute", p: "/kəmˈpjuːt/", d: "v. 计算", e: "compute the result" },
      { w: "conceal", p: "/kənˈsiːl/", d: "v. 隐藏", e: "conceal the truth" },
      { w: "concentrate", p: "/ˈkɒnsntreɪt/", d: "v. 集中；专注", e: "concentrate on work" },
      { w: "concept", p: "/ˈkɒnsept/", d: "n. 概念", e: "a new concept" },
      { w: "concern", p: "/kənˈsɜːn/", d: "n. 关心；担忧 v. 涉及", e: "show concern" },
      { w: "conclude", p: "/kənˈkluːd/", d: "v. 结论；结束", e: "conclude the meeting" },
      { w: "concrete", p: "/ˈkɒŋkriːt/", d: "adj. 具体的 n. 混凝土", e: "concrete evidence" },
      { w: "condemn", p: "/kənˈdem/", d: "v. 谴责；判刑", e: "condemn the act" },
      { w: "conduct", p: "/kənˈdʌkt/", d: "v. 进行；引导 /ˈkɒndʌkt/ n. 行为", e: "conduct research" },
      { w: "conference", p: "/ˈkɒnfərəns/", d: "n. 会议", e: "a press conference" },
      { w: "confess", p: "/kənˈfes/", d: "v. 承认；坦白", e: "confess a mistake" },
      { w: "confident", p: "/ˈkɒnfɪdənt/", d: "adj. 自信的", e: "a confident smile" },
      { w: "confirm", p: "/kənˈfɜːm/", d: "v. 确认；证实", e: "confirm the booking" },
      { w: "conflict", p: "/ˈkɒnflɪkt/", d: "n. 冲突 v. 抵触", e: "a conflict of interest" },
      { w: "conform", p: "/kənˈfɔːm/", d: "v. 遵守；符合", e: "conform to the rules" },
      { w: "confront", p: "/kənˈfrʌnt/", d: "v. 面对；对抗", e: "confront the problem" },
      { w: "confuse", p: "/kənˈfjuːz/", d: "v. 使困惑", e: "confuse A with B" },
      { w: "connect", p: "/kəˈnekt/", d: "v. 连接；联系", e: "connect to Wi-Fi" },
      { w: "conscious", p: "/ˈkɒnʃəs/", d: "adj. 有意识的；清醒的", e: "become conscious" },
      { w: "consequence", p: "/ˈkɒnsɪkwəns/", d: "n. 结果；后果", e: "face the consequence" },
      { w: "consider", p: "/kənˈsɪdə/", d: "v. 考虑；认为", e: "consider the option" },
      { w: "consist", p: "/kənˈsɪst/", d: "v. 组成", e: "consist of three parts" },
      { w: "constant", p: "/ˈkɒnstənt/", d: "adj. 不断的；恒定的", e: "constant change" },
      { w: "construct", p: "/kənˈstrʌkt/", d: "v. 建造；构建", e: "construct a bridge" },
      { w: "consult", p: "/kənˈsʌlt/", d: "v. 咨询；查阅", e: "consult a doctor" },
      { w: "consume", p: "/kənˈsjuːm/", d: "v. 消耗；消费", e: "consume energy" },
      { w: "contact", p: "/ˈkɒntækt/", d: "n. 接触；联系人 v. 联系", e: "lose contact" },
      { w: "contain", p: "/kənˈteɪn/", d: "v. 包含；遏制", e: "the box contains books" },
      { w: "contemporary", p: "/kənˈtemprəri/", d: "adj. 当代的；同时代的", e: "contemporary art" },
      { w: "content", p: "/ˈkɒntent/", d: "n. 内容；目录 adj. 满足的", e: "the content of the book" },
      { w: "contest", p: "/ˈkɒntest/", d: "n. 竞赛 v. 争夺", e: "a singing contest" },
      { w: "context", p: "/ˈkɒntekst/", d: "n. 上下文；背景", e: "in context" },
      { w: "contrast", p: "/ˈkɒntrɑːst/", d: "n. 对比 v. 对照", e: "by contrast" },
      { w: "contribute", p: "/kənˈtrɪbjut/", d: "v. 贡献；投稿", e: "contribute to society" },
      { w: "controversial", p: "/ˌkɒntrəˈvɜːʃl/", d: "adj. 有争议的", e: "a controversial topic" },
      { w: "convince", p: "/kənˈvɪns/", d: "v. 使信服", e: "convince the jury" },
      { w: "cooperate", p: "/kəʊˈɒpəreɪt/", d: "v. 合作", e: "cooperate with others" },
      { w: "coordinate", p: "/kəʊˈɔːdɪneɪt/", d: "v. 协调", e: "coordinate the event" },
      { w: "corporate", p: "/ˈkɔːpərət/", d: "adj. 公司的；团体的", e: "corporate culture" },
    ],
  },
  {
    day: 7,
    words: [
      { w: "correct", p: "/kəˈrekt/", d: "adj. 正确的 v. 纠正", e: "correct the error" },
      { w: "correspond", p: "/ˌkɒrəˈspɒnd/", d: "v. 相符；通信", e: "correspond to the data" },
      { w: "costly", p: "/ˈkɒstli/", d: "adj. 昂贵的", e: "a costly mistake" },
      { w: "council", p: "/ˈkaʊnsl/", d: "n. 委员会；理事会", e: "the city council" },
      { w: "counsel", p: "/ˈkaʊnsl/", d: "n. 忠告；律师 v. 劝告", e: "seek counsel" },
      { w: "counter", p: "/ˈkaʊntə/", d: "n. 柜台；计数器 v. 反驳", e: "behind the counter" },
      { w: "court", p: "/kɔːt/", d: "n. 法院；球场；宫廷", e: "a tennis court" },
      { w: "crash", p: "/kræʃ/", d: "v. 坠毁；碰撞 n. 崩溃", e: "a car crash" },
      { w: "create", p: "/kriˈeɪt/", d: "v. 创造", e: "create value" },
      { w: "creative", p: "/kriˈeɪtɪv/", d: "adj. 有创造力的", e: "a creative mind" },
      { w: "credit", p: "/ˈkredɪt/", d: "n. 信用；学分；赞扬", e: "a credit card" },
      { w: "crisis", p: "/ˈkraɪsɪs/", d: "n. 危机", e: "an economic crisis" },
      { w: "critic", p: "/ˈkrɪtɪk/", d: "n. 批评家；评论员", e: "a literary critic" },
      { w: "critical", p: "/ˈkrɪtɪkl/", d: "adj. 关键的；批评的", e: "a critical moment" },
      { w: "criticize", p: "/ˈkrɪtɪsaɪz/", d: "v. 批评", e: "criticize the policy" },
      { w: "crowd", p: "/kraʊd/", d: "n. 人群 v. 拥挤", e: "a large crowd" },
      { w: "cruel", p: "/ˈkruːəl/", d: "adj. 残忍的", e: "a cruel joke" },
      { w: "crude", p: "/kruːd/", d: "adj. 粗糙的；天然的", e: "crude oil" },
      { w: "cultivate", p: "/ˈkʌltɪveɪt/", d: "v. 培养；耕作", e: "cultivate a habit" },
      { w: "curiosity", p: "/ˌkjʊəriˈɒsəti/", d: "n. 好奇心", e: "out of curiosity" },
      { w: "current", p: "/ˈkʌrənt/", d: "adj. 当前的 n. 电流", e: "current affairs" },
      { w: "cycle", p: "/ˈsaɪkl/", d: "n. 循环；自行车 v. 循环", e: "the life cycle" },
      { w: "damage", p: "/ˈdæmɪdʒ/", d: "n. 损害 v. 损害", e: "cause damage" },
      { w: "dazzle", p: "/ˈdæzl/", d: "v. 使眩目；使赞叹", e: "dazzle the audience" },
      { w: "debate", p: "/dɪˈbeɪt/", d: "n. 辩论 v. 辩论", e: "a heated debate" },
      { w: "decay", p: "/dɪˈkeɪ/", d: "v. 腐烂；衰退 n. 衰退", e: "tooth decay" },
      { w: "deceive", p: "/dɪˈsiːv/", d: "v. 欺骗", e: "deceive the public" },
      { w: "decent", p: "/ˈdiːsnt/", d: "adj. 体面的；相当的", e: "a decent job" },
      { w: "decisive", p: "/dɪˈsaɪsɪv/", d: "adj. 决定性的", e: "a decisive victory" },
      { w: "decline", p: "/dɪˈklaɪn/", d: "v. 下降；拒绝 n. 衰退", e: "decline an offer" },
      { w: "dedicate", p: "/ˈdedɪkeɪt/", d: "v. 致力于", e: "dedicate to research" },
      { w: "deep", p: "/diːp/", d: "adj. 深的；深刻的", e: "deep thinking" },
      { w: "defect", p: "/ˈdiːfekt/", d: "n. 缺陷 v. 背叛", e: "a genetic defect" },
      { w: "defend", p: "/dɪˈfend/", d: "v. 防御；辩护", e: "defend one's rights" },
      { w: "define", p: "/dɪˈfaɪn/", d: "v. 定义", e: "define the term" },
      { w: "degree", p: "/dɪˈɡriː/", d: "n. 程度；学位", e: "a master's degree" },
      { w: "deliberate", p: "/dɪˈlɪbərət/", d: "adj. 故意的；深思的", e: "a deliberate act" },
      { w: "delicate", p: "/ˈdelɪkət/", d: "adj. 精致的；脆弱的", e: "a delicate situation" },
      { w: "deliver", p: "/dɪˈlɪvə/", d: "v. 递送；发表", e: "deliver a speech" },
      { w: "demonstrate", p: "/ˈdemənstreɪt/", d: "v. 证明；演示", e: "demonstrate the method" },
    ],
  },
  {
    day: 8,
    words: [
      { w: "dense", p: "/dens/", d: "adj. 密集的；浓的", e: "dense fog" },
      { w: "deny", p: "/dɪˈnaɪ/", d: "v. 否认；拒绝", e: "deny the accusation" },
      { w: "depart", p: "/dɪˈpɑːt/", d: "v. 离开；出发", e: "depart from the station" },
      { w: "dependent", p: "/dɪˈpendənt/", d: "adj. 依赖的", e: "dependent on parents" },
      { w: "depress", p: "/dɪˈpres/", d: "v. 使沮丧；压下", e: "depress the economy" },
      { w: "derive", p: "/dɪˈraɪv/", d: "v. 源于；获得", e: "derive from experience" },
      { w: "describe", p: "/dɪˈskraɪb/", d: "v. 描述", e: "describe the scene" },
      { w: "desert", p: "/ˈdezət/", d: "n. 沙漠 v. 抛弃 /dɪˈzɜːt/", e: "a hot desert" },
      { w: "deserve", p: "/dɪˈzɜːv/", d: "v. 应得", e: "deserve praise" },
      { w: "design", p: "/dɪˈzaɪn/", d: "v. 设计 n. 设计", e: "design a logo" },
      { w: "desire", p: "/dɪˈzaɪə/", d: "n. 渴望 v. 渴望", e: "a strong desire" },
      { w: "despair", p: "/dɪˈspeə/", d: "n. 绝望 v. 绝望", e: "in despair" },
      { w: "desperate", p: "/ˈdespərət/", d: "adj. 绝望的；拼命的", e: "a desperate cry" },
      { w: "destroy", p: "/dɪˈstrɔɪ/", d: "v. 摧毁", e: "destroy the bridge" },
      { w: "detail", p: "/ˈdiːteɪl/", d: "n. 细节 v. 详述", e: "pay attention to detail" },
      { w: "detect", p: "/dɪˈtekt/", d: "v. 察觉；探测", e: "detect a signal" },
      { w: "device", p: "/dɪˈvaɪs/", d: "n. 装置；设备", e: "a mobile device" },
      { w: "devote", p: "/dɪˈvəʊt/", d: "v. 奉献", e: "devote time to study" },
      { w: "dim", p: "/dɪm/", d: "adj. 昏暗的；模糊的", e: "a dim light" },
      { w: "diminish", p: "/dɪˈmɪnɪʃ/", d: "v. 减少；削弱", e: "diminish in value" },
      { w: "dire", p: "/ˈdaɪə/", d: "adj. 可怕的；紧急的", e: "a dire situation" },
      { w: "discipline", p: "/ˈdɪsəplɪn/", d: "n. 纪律；学科 v. 训练", e: "self-discipline" },
      { w: "disclose", p: "/dɪsˈkləʊz/", d: "v. 披露", e: "disclose the truth" },
      { w: "discount", p: "/ˈdɪskaʊnt/", d: "n. 折扣 v. 打折", e: "a 20% discount" },
      { w: "discourage", p: "/dɪsˈkʌrɪdʒ/", d: "v. 使气馁", e: "discourage cheating" },
      { w: "discover", p: "/dɪsˈkʌvə/", d: "v. 发现", e: "discover a new star" },
      { w: "discriminate", p: "/dɪˈskrɪmɪneɪt/", d: "v. 歧视；区分", e: "discriminate against women" },
      { w: "disguise", p: "/dɪsˈɡaɪz/", d: "v. 伪装 n. 伪装", e: "in disguise" },
      { w: "disorder", p: "/dɪsˈɔːdə/", d: "n. 混乱；失调", e: "a sleep disorder" },
      { w: "display", p: "/dɪˈspleɪ/", d: "v. 展示 n. 陈列", e: "on display" },
      { w: "dispose", p: "/dɪˈspəʊz/", d: "v. 处理；布置", e: "dispose of waste" },
      { w: "distinct", p: "/dɪˈstɪŋkt/", d: "adj. 明显的；独特的", e: "a distinct accent" },
      { w: "distort", p: "/dɪˈstɔːt/", d: "v. 扭曲", e: "distort the facts" },
      { w: "distribute", p: "/dɪˈstrɪbjuːt/", d: "v. 分配；分发", e: "distribute leaflets" },
      { w: "disturb", p: "/dɪˈstɜːb/", d: "v. 打扰", e: "sorry to disturb" },
      { w: "diverse", p: "/daɪˈvɜːs/", d: "adj. 多样的", e: "a diverse culture" },
      { w: "divide", p: "/dɪˈvaɪd/", d: "v. 分开；除", e: "divide the work" },
      { w: "dividend", p: "/ˈdɪvɪdend/", d: "n. 红利；股息", e: "pay a dividend" },
      { w: "divine", p: "/dɪˈvaɪn/", d: "adj. 神圣的；极好的", e: "divine music" },
      { w: "document", p: "/ˈdɒkjumənt/", d: "n. 文件 v. 记录", e: "a legal document" },
    ],
  },
  {
    day: 9,
    words: [
      { w: "domain", p: "/dəˈmeɪn/", d: "n. 领域；域名", e: "in the domain of science" },
      { w: "domestic", p: "/dəˈmestɪk/", d: "adj. 国内的；家庭的", e: "domestic market" },
      { w: "dominant", p: "/ˈdɒmɪnənt/", d: "adj. 主导的", e: "a dominant role" },
      { w: "donate", p: "/dəʊˈneɪt/", d: "v. 捐赠", e: "donate blood" },
      { w: "doubt", p: "/daʊt/", d: "n. 怀疑 v. 怀疑", e: "no doubt" },
      { w: "dramatic", p: "/drəˈmætɪk/", d: "adj. 戏剧性的；显著的", e: "a dramatic change" },
      { w: "drastic", p: "/ˈdrɑːstɪk/", d: "adj. 激烈的；极端的", e: "drastic measures" },
      { w: "drawback", p: "/ˈdrɔːbæk/", d: "n. 缺点；不利", e: "a major drawback" },
      { w: "drought", p: "/draʊt/", d: "n. 干旱", e: "a severe drought" },
      { w: "drown", p: "/draʊn/", d: "v. 淹死；淹没", e: "drown in work" },
      { w: "dual", p: "/ˈdjuːəl/", d: "adj. 双重的", e: "a dual role" },
      { w: "dubious", p: "/ˈdjuːbiəs/", d: "adj. 可疑的；犹豫的", e: "a dubious claim" },
      { w: "durable", p: "/ˈdjʊərəbl/", d: "adj. 耐用的", e: "durable goods" },
      { w: "dynamic", p: "/daɪˈnæmɪk/", d: "adj. 动态的；有活力的", e: "a dynamic team" },
      { w: "eager", p: "/ˈiːɡə/", d: "adj. 渴望的", e: "eager to learn" },
      { w: "earn", p: "/ɜːn/", d: "v. 赚取；赢得", e: "earn a living" },
      { w: "ease", p: "/iːz/", d: "n. 容易；安逸 v. 缓和", e: "with ease" },
      { w: "echo", p: "/ˈekəʊ/", d: "n. 回声 v. 回响", e: "echo one's words" },
      { w: "economy", p: "/ɪˈkɒnəmi/", d: "n. 经济；节约", e: "the national economy" },
      { w: "edit", p: "/ˈedɪt/", d: "v. 编辑", e: "edit a video" },
      { w: "educate", p: "/ˈedʒukeɪt/", d: "v. 教育", e: "educate the public" },
      { w: "effective", p: "/ɪˈfektɪv/", d: "adj. 有效的", e: "an effective method" },
      { w: "efficient", p: "/ɪˈfɪʃnt/", d: "adj. 高效的", e: "an efficient worker" },
      { w: "elaborate", p: "/ɪˈlæbərət/", d: "adj. 精心制作的 v. 详述", e: "an elaborate plan" },
      { w: "elderly", p: "/ˈeldəli/", d: "adj. 年长的 n. 老人", e: "care for the elderly" },
      { w: "elect", p: "/ɪˈlekt/", d: "v. 选举；选择", e: "elect a president" },
      { w: "elegant", p: "/ˈelɪɡənt/", d: "adj. 优雅的", e: "an elegant dress" },
      { w: "element", p: "/ˈelɪmənt/", d: "n. 元素；要素", e: "a key element" },
      { w: "elevate", p: "/ˈelɪveɪt/", d: "v. 提升；抬高", e: "elevate one's mood" },
      { w: "eliminate", p: "/ɪˈlɪmɪneɪt/", d: "v. 消除；淘汰", e: "eliminate poverty" },
      { w: "elite", p: "/eɪˈliːt/", d: "n. 精英 adj. 精英的", e: "the scientific elite" },
      { w: "emerge", p: "/ɪˈmɜːdʒ/", d: "v. 出现；浮现", e: "emerge from the crisis" },
      { w: "emotion", p: "/ɪˈməʊʃn/", d: "n. 情感", e: "show emotion" },
      { w: "emphasize", p: "/ˈemfəsaɪz/", d: "v. 强调", e: "emphasize the point" },
      { w: "employ", p: "/ɪmˈplɔɪ/", d: "v. 雇用；使用", e: "employ staff" },
      { w: "enable", p: "/ɪˈneɪbl/", d: "v. 使能够", e: "enable success" },
      { w: "encounter", p: "/ɪnˈkaʊntə/", d: "v. 遭遇 n. 相遇", e: "encounter a problem" },
      { w: "endure", p: "/ɪnˈdjʊə/", d: "v. 忍受；持续", e: "endure the pain" },
      { w: "energy", p: "/ˈenədʒi/", d: "n. 能量；精力", e: "save energy" },
      { w: "enforce", p: "/ɪnˈfɔːs/", d: "v. 执行；强制", e: "enforce the law" },
    ],
  },
  {
    day: 10,
    words: [
      { w: "engage", p: "/ɪnˈɡeɪdʒ/", d: "v. 从事；吸引", e: "engage in discussion" },
      { w: "enhance", p: "/ɪnˈhɑːns/", d: "v. 提高；增强", e: "enhance performance" },
      { w: "enjoy", p: "/ɪnˈdʒɔɪ/", d: "v. 享受", e: "enjoy the music" },
      { w: "enlarge", p: "/ɪnˈlɑːdʒ/", d: "v. 扩大", e: "enlarge the image" },
      { w: "enormous", p: "/ɪˈnɔːməs/", d: "adj. 巨大的", e: "an enormous amount" },
      { w: "ensure", p: "/ɪnˈʃʊə/", d: "v. 确保", e: "ensure safety" },
      { w: "enter", p: "/ˈentə/", d: "v. 进入", e: "enter the room" },
      { w: "entire", p: "/ɪnˈtaɪə/", d: "adj. 整个的", e: "the entire world" },
      { w: "entity", p: "/ˈentəti/", d: "n. 实体", e: "a legal entity" },
      { w: "environment", p: "/ɪnˈvaɪrənmənt/", d: "n. 环境", e: "protect the environment" },
      { w: "envy", p: "/ˈenvi/", d: "n. 嫉妒 v. 羡慕", e: "envy his success" },
      { w: "equal", p: "/ˈiːkwəl/", d: "adj. 平等的；相等的 v. 等于", e: "equal rights" },
      { w: "equip", p: "/ɪˈkwɪp/", d: "v. 装备；配备", e: "equip with tools" },
      { w: "equivalent", p: "/ɪˈkwɪvələnt/", d: "adj. 等价的 n. 等价物", e: "the equivalent of" },
      { w: "erase", p: "/ɪˈreɪz/", d: "v. 擦除", e: "erase the mistake" },
      { w: "error", p: "/ˈerə/", d: "n. 错误", e: "an error in judgment" },
      { w: "essential", p: "/ɪˈsenʃl/", d: "adj. 必要的 n. 要素", e: "essential skills" },
      { w: "establish", p: "/ɪˈstæblɪʃ/", d: "v. 建立", e: "establish a company" },
      { w: "estimate", p: "/ˈestɪmeɪt/", d: "v. 估计 n. 估计", e: "estimate the cost" },
      { w: "ethnic", p: "/ˈeθnɪk/", d: "adj. 种族的", e: "ethnic minorities" },
      { w: "evaluate", p: "/ɪˈvæljueɪt/", d: "v. 评价；评估", e: "evaluate the plan" },
      { w: "evidence", p: "/ˈevɪdəns/", d: "n. 证据", e: "strong evidence" },
      { w: "exact", p: "/ɪɡˈzækt/", d: "adj. 精确的", e: "the exact number" },
      { w: "exceed", p: "/ɪkˈsiːd/", d: "v. 超过", e: "exceed the limit" },
      { w: "excellent", p: "/ˈeksələnt/", d: "adj. 优秀的", e: "excellent work" },
      { w: "exception", p: "/ɪkˈsepʃn/", d: "n. 例外", e: "with few exceptions" },
      { w: "excess", p: "/ɪkˈses/", d: "n. 过量 adj. 过量的", e: "in excess" },
      { w: "exchange", p: "/ɪksˈtʃeɪndʒ/", d: "v. 交换 n. 交换", e: "exchange ideas" },
      { w: "exclude", p: "/ɪkˈskluːd/", d: "v. 排除", e: "exclude the possibility" },
      { w: "exclusive", p: "/ɪkˈskluːsɪv/", d: "adj. 独有的；排外的", e: "an exclusive interview" },
      { w: "execute", p: "/ˈeksɪkjuːt/", d: "v. 执行；处决", e: "execute a plan" },
      { w: "exert", p: "/ɪɡˈzɜːt/", d: "v. 施加；运用", e: "exert pressure" },
      { w: "exhaust", p: "/ɪɡˈzɔːst/", d: "v. 耗尽；使筋疲力尽", e: "exhaust one's patience" },
      { w: "exhibit", p: "/ɪɡˈzɪbɪt/", d: "v. 展示 n. 展品", e: "exhibit courage" },
      { w: "exist", p: "/ɪɡˈzɪst/", d: "v. 存在", e: "problems still exist" },
      { w: "expand", p: "/ɪkˈspænd/", d: "v. 扩张；扩展", e: "expand the business" },
      { w: "expect", p: "/ɪkˈspekt/", d: "v. 期待；预期", e: "expect a call" },
      { w: "expert", p: "/ˈekspɜːt/", d: "n. 专家 adj. 专业的", e: "an expert in law" },
      { w: "expire", p: "/ɪkˈspaɪə/", d: "v. 到期；失效", e: "the contract expires" },
      { w: "explicit", p: "/ɪkˈsplɪsɪt/", d: "adj. 明确的", e: "explicit instructions" },
    ],
  },
];

export const VOCAB_TOTAL = 400;
export const VOCAB_DAILY = 40;

// 把整份词库压缩成一段文本（单词 + 音标 + 释义），供「把词库发给 AI」时注入对话。
export function vocabText(): string {
  const lines: string[] = [`四级核心词汇 ${VOCAB_TOTAL} 词（10 天 × 每天 ${VOCAB_DAILY} 词）：`];
  for (const g of VOCAB_DAYS) {
    lines.push(`Day ${g.day}:`);
    for (const w of g.words) {
      lines.push(`- ${w.w} ${w.p} ${w.d}`);
    }
  }
  return lines.join('\n');
}


